# Generated by Django 3.0.4 on 2020-05-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('main_image', models.ImageField(upload_to='blog/main_images/')),
                ('image1', models.ImageField(blank=True, upload_to='blog/optional_images')),
                ('image2', models.ImageField(blank=True, upload_to='blog/optional_images')),
                ('image3', models.ImageField(blank=True, upload_to='blog/optional_images')),
                ('image4', models.ImageField(blank=True, upload_to='blog/optional_images')),
                ('url', models.URLField(blank=True)),
            ],
        ),
    ]
